// <auto-generated />
using FinalProject_SapirTeper_OfirEinhoren.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject_SapirTeper_OfirEinhoren.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220401132402_AddBlockModel")]
    partial class AddBlockModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("FinalProject_SapirTeper_OfirEinhoren.Shared.Entities.Block", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("B_ActionSelected")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_UrlLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_UrlText")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockType")
                        .HasColumnType("TEXT");

                    b.Property<string>("IQ_Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("I_AnsOptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("I_FeedbackFalse")
                        .HasColumnType("TEXT");

                    b.Property<string>("I_FeedbackTrue")
                        .HasColumnType("TEXT");

                    b.Property<int>("I_NumberOfAns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("I_TrueAns")
                        .HasColumnType("TEXT");

                    b.Property<string>("I_Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("FinalProject_SapirTeper_OfirEinhoren.Shared.Entities.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FinalProject_SapirTeper_OfirEinhoren.Shared.Entities.Block", b =>
                {
                    b.HasOne("FinalProject_SapirTeper_OfirEinhoren.Shared.Entities.Project", "BlockProject")
                        .WithMany("ProjectBlocks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockProject");
                });

            modelBuilder.Entity("FinalProject_SapirTeper_OfirEinhoren.Shared.Entities.Project", b =>
                {
                    b.Navigation("ProjectBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
